In [284]:
import pandas as pd
import numpy as np

from spacy.lang.en import English

import matplotlib.pyplot as plt
%matplotlib inline

#Some of these packages will generate a ton of warnings...
import warnings
warnings.filterwarnings("ignore")

In [283]:
data = pd.read_csv('data/OnlineNewsPopularity/OnlineNewsPopularity.csv')
data.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [6]:
data.describe()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,354.530471,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184
std,214.163767,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749
min,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000
25%,164.000000,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000
50%,339.000000,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000
75%,542.000000,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000
max,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000

Attribute Information:

Number of Attributes: 61 (58 predictive attributes, 2 non-predictive, 1 goal field) 

Attribute Information: 
0. url: URL of the article (non-predictive) 
1. timedelta: Days between the article publication and the dataset acquisition (non-predictive) 
2. n_tokens_title: Number of words in the title 
3. n_tokens_content: Number of words in the content 
4. n_unique_tokens: Rate of unique words in the content 
5. n_non_stop_words: Rate of non-stop words in the content 
6. n_non_stop_unique_tokens: Rate of unique non-stop words in the content 
7. num_hrefs: Number of links 
8. num_self_hrefs: Number of links to other articles published by Mashable 
9. num_imgs: Number of images 
10. num_videos: Number of videos 
11. average_token_length: Average length of the words in the content 
12. num_keywords: Number of keywords in the metadata 
13. data_channel_is_lifestyle: Is data channel 'Lifestyle'? 
14. data_channel_is_entertainment: Is data channel 'Entertainment'? 
15. data_channel_is_bus: Is data channel 'Business'? 
16. data_channel_is_socmed: Is data channel 'Social Media'? 
17. data_channel_is_tech: Is data channel 'Tech'? 
18. data_channel_is_world: Is data channel 'World'? 
19. kw_min_min: Worst keyword (min. shares) 
20. kw_max_min: Worst keyword (max. shares) 
21. kw_avg_min: Worst keyword (avg. shares) 
22. kw_min_max: Best keyword (min. shares) 
23. kw_max_max: Best keyword (max. shares) 
24. kw_avg_max: Best keyword (avg. shares) 
25. kw_min_avg: Avg. keyword (min. shares) 
26. kw_max_avg: Avg. keyword (max. shares) 
27. kw_avg_avg: Avg. keyword (avg. shares) 
28. self_reference_min_shares: Min. shares of referenced articles in Mashable 
29. self_reference_max_shares: Max. shares of referenced articles in Mashable 
30. self_reference_avg_sharess: Avg. shares of referenced articles in Mashable 
31. weekday_is_monday: Was the article published on a Monday? 
32. weekday_is_tuesday: Was the article published on a Tuesday? 
33. weekday_is_wednesday: Was the article published on a Wednesday? 
34. weekday_is_thursday: Was the article published on a Thursday? 
35. weekday_is_friday: Was the article published on a Friday? 
36. weekday_is_saturday: Was the article published on a Saturday? 
37. weekday_is_sunday: Was the article published on a Sunday? 
38. is_weekend: Was the article published on the weekend? 
39. LDA_00: Closeness to LDA topic 0 
40. LDA_01: Closeness to LDA topic 1 
41. LDA_02: Closeness to LDA topic 2 
42. LDA_03: Closeness to LDA topic 3 
43. LDA_04: Closeness to LDA topic 4 
44. global_subjectivity: Text subjectivity 
45. global_sentiment_polarity: Text sentiment polarity 
46. global_rate_positive_words: Rate of positive words in the content 
47. global_rate_negative_words: Rate of negative words in the content 
48. rate_positive_words: Rate of positive words among non-neutral tokens 
49. rate_negative_words: Rate of negative words among non-neutral tokens 
50. avg_positive_polarity: Avg. polarity of positive words 
51. min_positive_polarity: Min. polarity of positive words 
52. max_positive_polarity: Max. polarity of positive words 
53. avg_negative_polarity: Avg. polarity of negative words 
54. min_negative_polarity: Min. polarity of negative words 
55. max_negative_polarity: Max. polarity of negative words 
56. title_subjectivity: Title subjectivity 
57. title_sentiment_polarity: Title polarity 
58. abs_title_subjectivity: Absolute subjectivity level 
59. abs_title_sentiment_polarity: Absolute polarity level 
60. shares: Number of shares (target)

In [10]:
data.isna().mean()

url                               0.0
 timedelta                        0.0
 n_tokens_title                   0.0
 n_tokens_content                 0.0
 n_unique_tokens                  0.0
 n_non_stop_words                 0.0
 n_non_stop_unique_tokens         0.0
 num_hrefs                        0.0
 num_self_hrefs                   0.0
 num_imgs                         0.0
 num_videos                       0.0
 average_token_length             0.0
 num_keywords                     0.0
 data_channel_is_lifestyle        0.0
 data_channel_is_entertainment    0.0
 data_channel_is_bus              0.0
 data_channel_is_socmed           0.0
 data_channel_is_tech             0.0
 data_channel_is_world            0.0
 kw_min_min                       0.0
 kw_max_min                       0.0
 kw_avg_min                       0.0
 kw_min_max                       0.0
 kw_max_max                       0.0
 kw_avg_max                       0.0
 kw_min_avg                       0.0
 kw_max_avg                       0.0
 kw_avg_avg                       0.0
 self_reference_min_shares        0.0
 self_reference_max_shares        0.0
                                 ...
 weekday_is_monday                0.0
 weekday_is_tuesday               0.0
 weekday_is_wednesday             0.0
 weekday_is_thursday              0.0
 weekday_is_friday                0.0
 weekday_is_saturday              0.0
 weekday_is_sunday                0.0
 is_weekend                       0.0
 LDA_00                           0.0
 LDA_01                           0.0
 LDA_02                           0.0
 LDA_03                           0.0
 LDA_04                           0.0
 global_subjectivity              0.0
 global_sentiment_polarity        0.0
 global_rate_positive_words       0.0
 global_rate_negative_words       0.0
 rate_positive_words              0.0
 rate_negative_words              0.0
 avg_positive_polarity            0.0
 min_positive_polarity            0.0
 max_positive_polarity            0.0
 avg_negative_polarity            0.0
 min_negative_polarity            0.0
 max_negative_polarity            0.0
 title_subjectivity               0.0
 title_sentiment_polarity         0.0
 abs_title_subjectivity           0.0
 abs_title_sentiment_polarity     0.0
 shares                           0.0
Length: 61, dtype: float64

In [113]:
#dropping non-predictive columns
data.drop(['url', ' timedelta'], axis=1, inplace=True)
data.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,0.0,4.680365,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,0.0,4.913725,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,0.0,4.393365,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,0.0,4.404896,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,0.0,4.682836,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [114]:
#Lifestyle category
data_lifestyle = data[data[' data_channel_is_lifestyle'] == 1]
data_lifestyle.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
6,8.0,960.0,0.418163,1.0,0.549834,21.0,20.0,20.0,0.0,4.654167,...,0.100000,1.0,-0.224479,-0.5000,-0.050,0.000000,0.000000,0.500000,0.000000,556
11,10.0,187.0,0.666667,1.0,0.800000,7.0,0.0,1.0,0.0,4.657754,...,0.200000,0.7,-0.262500,-0.4000,-0.125,0.000000,0.000000,0.500000,0.000000,1900
18,11.0,103.0,0.689320,1.0,0.806452,3.0,1.0,1.0,0.0,4.844660,...,0.033333,0.5,-0.125000,-0.1250,-0.125,0.857143,-0.714286,0.357143,0.714286,5700
28,10.0,243.0,0.619247,1.0,0.824427,1.0,1.0,0.0,0.0,4.382716,...,0.136364,0.6,-0.177500,-0.3125,-0.125,0.000000,0.000000,0.500000,0.000000,462
34,8.0,204.0,0.586207,1.0,0.698413,7.0,2.0,1.0,0.0,4.671569,...,0.100000,1.0,-0.400000,-0.4000,-0.400,0.000000,0.000000,0.500000,0.000000,3600

In [115]:
#entertainment category
data_entertainment = data[data[' data_channel_is_entertainment'] == 1]
data_entertainment.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,0.0,4.680365,...,0.100000,0.70,-0.350000,-0.6,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
3,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,0.0,4.404896,...,0.136364,0.80,-0.369697,-0.6,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
39,14.0,194.0,0.764706,1.0,0.840336,4.0,4.0,0.0,1.0,4.520619,...,0.100000,1.00,0.000000,0.0,0.000000,0.400000,0.100000,0.100000,0.100000,2100
47,12.0,161.0,0.668831,1.0,0.752381,5.0,4.0,0.0,6.0,4.453416,...,0.100000,0.85,-0.363889,-0.8,-0.125000,0.583333,0.250000,0.083333,0.250000,1200
53,11.0,454.0,0.566079,1.0,0.754513,5.0,3.0,1.0,0.0,4.885463,...,0.100000,1.00,-0.215476,-0.5,-0.100000,0.427273,0.168182,0.072727,0.168182,4600

In [116]:
#business category
data_business = data[data[' data_channel_is_bus'] == 1]
data_business.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
1,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,0.0,4.913725,...,0.033333,0.700000,-0.118750,-0.125,-0.100000,0.0,0.0,0.5,0.0,711
2,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,0.0,4.393365,...,0.100000,1.000000,-0.466667,-0.800,-0.133333,0.0,0.0,0.5,0.0,1500
17,8.0,397.0,0.624679,1.0,0.805668,11.0,0.0,1.0,0.0,5.445844,...,0.033333,1.000000,-0.144643,-0.200,-0.100000,0.0,0.0,0.5,0.0,3100
24,13.0,244.0,0.560000,1.0,0.680272,3.0,2.0,1.0,0.0,4.422131,...,0.136364,0.433333,-0.456481,-1.000,-0.125000,0.7,-0.4,0.2,0.4,852
29,11.0,723.0,0.490934,1.0,0.642241,18.0,1.0,1.0,0.0,5.228216,...,0.033333,1.000000,-0.213889,-0.600,-0.100000,0.5,0.5,0.0,0.5,425

In [117]:
#socmed category
data_socmed = data[data[' data_channel_is_socmed'] == 1]
data_socmed.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
37,8.0,257.0,0.568093,1.0,0.670968,9.0,7.0,0.0,1.0,4.638132,...,0.033333,0.6,-0.392857,-0.50,-0.125,0.666667,-0.5,0.166667,0.5,2600
73,8.0,218.0,0.662983,1.0,0.688000,14.0,3.0,11.0,0.0,4.435780,...,0.100000,1.0,-0.237500,-0.25,-0.200,0.500000,0.5,0.000000,0.5,690
77,9.0,1226.0,0.410172,1.0,0.616959,10.0,10.0,1.0,1.0,4.393964,...,0.062500,1.0,-0.257738,-1.00,-0.100,0.000000,0.0,0.500000,0.0,4800
78,10.0,1121.0,0.450679,1.0,0.629464,15.0,11.0,1.0,0.0,4.790366,...,0.033333,1.0,-0.316667,-0.80,-0.150,0.000000,0.0,0.500000,0.0,851
96,9.0,168.0,0.778481,1.0,0.865385,6.0,4.0,11.0,0.0,4.678571,...,0.100000,1.0,-0.502083,-1.00,-0.150,1.000000,-1.0,0.500000,1.0,4800

In [163]:
#tech category
data_tech = data[data[' data_channel_is_tech'] == 1]
data_tech.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
4,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,0.0,4.682836,...,0.033333,1.0,-0.220192,-0.500,-0.050,0.454545,0.136364,0.045455,0.136364,505
5,10.0,370.0,0.559889,1.0,0.698198,2.0,2.0,0.0,0.0,4.359459,...,0.136364,0.6,-0.195000,-0.400,-0.100,0.642857,0.214286,0.142857,0.214286,855
7,12.0,989.0,0.433574,1.0,0.572108,20.0,20.0,20.0,0.0,4.617796,...,0.100000,1.0,-0.242778,-0.500,-0.050,1.000000,0.500000,0.500000,0.500000,891
8,11.0,97.0,0.670103,1.0,0.836735,2.0,0.0,0.0,0.0,4.855670,...,0.400000,0.8,-0.125000,-0.125,-0.125,0.125000,0.000000,0.375000,0.000000,3600
19,8.0,1207.0,0.410579,1.0,0.548969,24.0,24.0,42.0,0.0,4.716653,...,0.100000,1.0,-0.226786,-0.500,-0.050,0.500000,0.000000,0.000000,0.000000,17100

In [119]:
#world category
data_world = data[data[' data_channel_is_world'] == 1]
data_world.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
9,10.0,231.0,0.636364,1.0,0.797101,4.0,1.0,1.0,1.0,5.090909,...,0.10,0.50,-0.238095,-0.500000,-0.10,0.00,0.00,0.50,0.00,710
10,9.0,1248.0,0.490050,1.0,0.731638,11.0,0.0,1.0,0.0,4.617788,...,0.10,1.00,-0.415064,-1.000000,-0.10,0.00,0.00,0.50,0.00,2200
15,12.0,682.0,0.459542,1.0,0.634961,10.0,0.0,1.0,0.0,4.620235,...,0.05,0.60,-0.220150,-0.600000,-0.05,0.75,-0.25,0.25,0.25,1600
21,9.0,391.0,0.510256,1.0,0.650000,9.0,2.0,1.0,1.0,5.296675,...,0.05,0.35,-0.108333,-0.166667,-0.05,0.00,0.00,0.50,0.00,598
23,11.0,125.0,0.674797,1.0,0.797468,1.0,1.0,1.0,0.0,4.824000,...,0.10,0.60,0.000000,0.000000,0.00,0.45,0.40,0.05,0.40,1500

In [120]:
y_lifestyle = data_lifestyle.iloc[:,58]
y_lifestyle = pd.qcut(y_lifestyle, 2, labels=[0, 1])

y_entertainment = data_entertainment.iloc[:,58]
y_entertainment = pd.qcut(y_entertainment, 2, labels=[0, 1])

y_business = data_business.iloc[:,58]
y_business = pd.qcut(y_business, 2, labels=[0, 1])

y_socmed = data_socmed.iloc[:,58]
y_socmed = pd.qcut(y_socmed, 2, labels=[0, 1])

y_tech = data_tech.iloc[:,58]
y_tech = pd.qcut(y_tech, 2, labels=[0, 1])

y_world = data_world.iloc[:,58]
y_world = pd.qcut(y_world, 2, labels=[0, 1])

In [121]:
X_lifestyle = data_lifestyle.iloc[:,0:58]

X_entertainment = data_entertainment.iloc[:,0:58]

X_business = data_business.iloc[:,0:58]

X_socmed = data_socmed.iloc[:,0:58]

X_tech = data_tech.iloc[:,0:58]

X_world = data_world.iloc[:,0:58]

In [122]:
from sklearn.model_selection import train_test_split
X_train_lifestyle, X_test_lifestyle, y_train_lifestyle, y_test_lifestyle = train_test_split(X_lifestyle, y_lifestyle, test_size=0.3, random_state=1)

X_train_entertainment, X_test_entertainment, y_train_entertainment, y_test_entertainment = train_test_split(X_entertainment, y_entertainment, test_size=0.3, random_state=1)

X_train_business, X_test_business, y_train_business, y_test_business = train_test_split(X_business, y_business, test_size=0.3, random_state=1)

X_train_socmed, X_test_socmed, y_train_socmed, y_test_socmed = train_test_split(X_socmed, y_socmed, test_size=0.3, random_state=1)

X_train_tech, X_test_tech, y_train_tech, y_test_tech = train_test_split(X_tech, y_tech, test_size=0.3, random_state=1)

X_train_world, X_test_world, y_train_world, y_test_world = train_test_split(X_world, y_world, test_size=0.3, random_state=1)

In [123]:
from sklearn.preprocessing import StandardScaler
scaler_lifestyle = StandardScaler()
scaler_lifestyle.fit(X_train_lifestyle)
X_train_lifestyle = scaler_lifestyle.transform(X_train_lifestyle)
X_test_lifestyle = scaler_lifestyle.transform(X_test_lifestyle)

scaler_entertainment = StandardScaler()
scaler_entertainment.fit(X_train_entertainment)
X_train_entertainment = scaler_entertainment.transform(X_train_entertainment)
X_test_entertainment = scaler_entertainment.transform(X_test_entertainment)

scaler_business = StandardScaler()
scaler_business.fit(X_train_business)
X_train_business = scaler_business.transform(X_train_business)
X_test_business = scaler_business.transform(X_test_business)

scaler_socmed = StandardScaler()
scaler_socmed.fit(X_train_socmed)
X_train_socmed = scaler_socmed.transform(X_train_socmed)
X_test_socmed = scaler_socmed.transform(X_test_socmed)

scaler_tech = StandardScaler()
scaler_tech.fit(X_train_tech)
X_train_tech = scaler_tech.transform(X_train_tech)
X_test_tech = scaler_tech.transform(X_test_tech)

scaler_world = StandardScaler()
scaler_world.fit(X_train_world)
X_train_world = scaler_world.transform(X_train_world)
X_test_world = scaler_world.transform(X_test_world)

In [228]:
from sklearn.linear_model import LogisticRegression

LogReg_lifestyle = LogisticRegression()
LogReg_entertainment = LogisticRegression()
LogReg_business = LogisticRegression()
LogReg_socmed = LogisticRegression()
LogReg_tech = LogisticRegression()
LogReg_world = LogisticRegression()

LogReg_lifestyle.fit(X_train_lifestyle, y_train_lifestyle)
LogReg_entertainment.fit(X_train_entertainment, y_train_entertainment)
LogReg_business.fit(X_train_business, y_train_business)
LogReg_socmed.fit(X_train_socmed, y_train_socmed)
LogReg_tech.fit(X_train_tech, y_train_tech)
LogReg_world.fit(X_train_world, y_train_world)

print("Test Set Scores:")
print(f"Lifestyle Logistic regression score: {LogReg_lifestyle.score(X_test_lifestyle, y_test_lifestyle)}")
print(f"Entertainment Logistic regression score: {LogReg_entertainment.score(X_test_entertainment, y_test_entertainment)}")
print(f"Business Logistic regression score: {LogReg_business.score(X_test_business, y_test_business)}")
print(f"Social Media Logistic regression score: {LogReg_socmed.score(X_test_socmed, y_test_socmed)}")
print(f"Technology Logistic regression score: {LogReg_tech.score(X_test_tech, y_test_tech)}")
print(f"World Logistic regression score: {LogReg_world.score(X_test_world, y_test_world)}")

Test Set Scores:
Lifestyle Logistic regression score: 0.5444444444444444
Entertainment Logistic regression score: 0.6142587346553352
Business Logistic regression score: 0.6778487752928648
Social Media Logistic regression score: 0.6814921090387375
Technology Logistic regression score: 0.5939201451905626
World Logistic regression score: 0.6231712139185449

In [141]:
coef = LogReg_lifestyle.coef_
len(coef)
coef

array([[-0.00136712,  0.09493793, -0.1546672 , -0.47205134,  0.24887224,
         0.12665207, -0.04074317,  0.25422545,  0.09518089,  0.24759601,
        -0.00551447,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.13751969,  0.29552479, -0.23043446,
         0.08276999, -0.03342485, -0.2943826 , -0.07653702, -0.51181904,
         0.7009065 ,  0.29123995,  0.18347818, -0.22194513,  0.05028249,
        -0.04050374, -0.03307953, -0.07822167, -0.00225205,  0.09358511,
         0.04732876,  0.10343194,  0.06551827,  0.02734962, -0.05295751,
        -0.08824536,  0.01534011, -0.00670614, -0.14518408,  0.08644923,
        -0.02114744, -0.22171133, -0.12421358, -0.09747683,  0.10628684,
         0.0616221 ,  0.12968966, -0.12003422, -0.15979921, -0.0302078 ,
        -0.02014229, -0.02821978, -0.14652769]])

In [154]:
coef = LogReg_lifestyle.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                       feature      coef
25                  kw_avg_avg  0.700906
18                  kw_max_min  0.295525
26   self_reference_min_shares  0.291240
7                     num_imgs  0.254225
4     n_non_stop_unique_tokens  0.248872
9         average_token_length  0.247596
27   self_reference_max_shares  0.183478
17                  kw_min_min  0.137520
51       avg_negative_polarity  0.129690
5                    num_hrefs  0.126652

In [155]:
coef = LogReg_entertainment.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                        feature      coef
25                   kw_avg_avg  0.846454
18                   kw_max_min  0.378399
36                   is_weekend  0.171297
5                     num_hrefs  0.169107
34          weekday_is_saturday  0.132843
42          global_subjectivity  0.123603
46          rate_positive_words  0.119559
28   self_reference_avg_sharess  0.114909
35            weekday_is_sunday  0.103671
2               n_unique_tokens  0.097394

In [156]:
coef = LogReg_business.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                        feature      coef
25                   kw_avg_avg  1.728534
18                   kw_max_min  0.464082
46          rate_positive_words  0.453317
1              n_tokens_content  0.307927
47          rate_negative_words  0.246491
17                   kw_min_min  0.220877
36                   is_weekend  0.183300
45   global_rate_negative_words  0.181112
56       abs_title_subjectivity  0.178925
34          weekday_is_saturday  0.173177

In [157]:
coef = LogReg_socmed.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                       feature      coef
25                  kw_avg_avg  0.681680
37                      LDA_00  0.379885
3             n_non_stop_words  0.260554
22                  kw_avg_max  0.139845
56      abs_title_subjectivity  0.135327
35           weekday_is_sunday  0.117501
27   self_reference_max_shares  0.106463
43   global_sentiment_polarity  0.104093
36                  is_weekend  0.096932
10                num_keywords  0.095952

In [158]:
coef = LogReg_tech.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                        feature      coef
25                   kw_avg_avg  0.713272
4      n_non_stop_unique_tokens  0.207843
5                     num_hrefs  0.157703
1              n_tokens_content  0.154911
34          weekday_is_saturday  0.151814
17                   kw_min_min  0.146409
36                   is_weekend  0.145312
52        min_negative_polarity  0.145094
53        max_negative_polarity  0.131028
45   global_rate_negative_words  0.111154

In [159]:
coef = LogReg_world.coef_.transpose().flatten()
features = X_lifestyle.columns.values
coef_df = pd.DataFrame({"feature":features, 
                         "coef":coef})
coef_df.sort_values(by="coef", ascending=False).head(10)

                        feature      coef
25                   kw_avg_avg  0.585328
2               n_unique_tokens  0.440369
46          rate_positive_words  0.215736
26    self_reference_min_shares  0.211395
7                      num_imgs  0.197913
3              n_non_stop_words  0.188568
5                     num_hrefs  0.176575
36                   is_weekend  0.173873
37                       LDA_00  0.143230
45   global_rate_negative_words  0.131958

In [190]:
sample = range(0,58)
sample = np.array(sample)
sample = pd.DataFrame(sample).transpose()
sample

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57

In [192]:
print(LogReg_lifestyle.predict(sample))

[0]

In [ ]:
#hypertuning for lifestyle
train_scores=[]
#test_scores = []
validation_scores = []

C_range = np.array([0.1,\
                1,10,100,1000,10000,100000,1000000,10000000])

for c in C_range:
    LogReg_lifestyle = LogisticRegression(C = c,random_state=1)
    LogReg_lifestyle.fit(X_train_lifestyle,y_train_lifestyle)
    
    # train on traning set
    train_scores.append(LogReg_lifestyle.score(X_train_lifestyle,y_train_lifestyle))
    # score on validation set
    validation_scores.append(LogReg_lifestyle.score(X_test_lifestyle,y_test_lifestyle))

In [ ]:
plt.figure()
plt.plot(C_range, train_scores,label="Train Score",marker='.')
plt.plot(C_range, validation_scores,label="Validation Scores",marker='.')

#plt.plot(C_range, test_scores,label="Test Score",marker='.')

plt.xscale('log')
plt.xlabel('C value for lifestyle category')
plt.ylabel('Accuracy')
plt.legend()
plt.show();

In [206]:
#lifestyle mean dataframe to be concatenated with input
Xmean_lifestyle = X_lifestyle.iloc[:,9:].mean()
dfmean_lifestyle = pd.DataFrame(Xmean_lifestyle).T
dfmean_lifestyle

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.588096,8.229633,1.0,0.0,0.0,0.0,0.0,0.0,40.58504,1609.065526,...,0.38288,0.094821,0.827612,-0.263051,-0.551274,-0.103328,0.286105,0.109075,0.347321,0.173258

In [207]:
#entertainment mean dataframe to be concatenated with input
Xmean_entertainment = X_entertainment.iloc[:,9:].mean()
dfmean_entertainment = pd.DataFrame(Xmean_entertainment).T
dfmean_entertainment

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.476815,6.924897,0.0,1.0,0.0,0.0,0.0,0.0,20.929857,1055.922474,...,0.365793,0.093508,0.797694,-0.294138,-0.587706,-0.110623,0.315796,0.064617,0.321031,0.171817

In [208]:
#business mean dataframe to be concatenated with input
Xmean_business = X_business.iloc[:,9:].mean()
dfmean_business = pd.DataFrame(Xmean_business).T
dfmean_business

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.688022,6.489613,0.0,0.0,1.0,0.0,0.0,0.0,29.26558,1042.227264,...,0.353285,0.086631,0.768,-0.24282,-0.480184,-0.109198,0.249068,0.08019,0.340758,0.139082

In [209]:
#social media mean dataframe to be concatenated with input
Xmean_socmed = X_socmed.iloc[:,9:].mean()
dfmean_socmed = pd.DataFrame(Xmean_socmed).T
dfmean_socmed

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.632582,6.552303,0.0,0.0,0.0,1.0,0.0,0.0,37.327163,1193.96108,...,0.358041,0.078172,0.783512,-0.257356,-0.521296,-0.111832,0.260528,0.097425,0.350673,0.153179

In [210]:
#technology mean dataframe to be concatenated with input
Xmean_tech = X_tech.iloc[:,9:].mean()
dfmean_tech = pd.DataFrame(Xmean_tech).T
dfmean_tech

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.582124,7.775932,0.0,0.0,0.0,0.0,1.0,0.0,29.975225,1154.60076,...,0.357061,0.099166,0.771912,-0.22877,-0.451262,-0.102695,0.253097,0.086359,0.344688,0.136037

In [212]:
#world mean dataframe to be concatenated with input
Xmean_world = X_world.iloc[:,9:].mean()
dfmean_world = pd.DataFrame(Xmean_world).T
dfmean_world

,average_token_length,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,kw_min_min,kw_max_min,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,4.678121,7.289664,0.0,0.0,0.0,0.0,0.0,1.0,15.76872,1038.022039,...,0.324549,0.088488,0.69897,-0.252285,-0.560709,-0.093905,0.24359,0.030061,0.361153,0.127724

Website inputs

In [254]:
title = "Who are you supposed to sing 'Happy Birthday' to when washing your hands?"
body = "This morning I sang Happy Birthday to You to myself in the bathroom even though it isn't my birthday. It felt wrong. I was washing my hands, as I've done approximately 50 times over the past two days, because I've now joined the masses of paranoid people worried about contracting the new coronavirus (which results in the disease that's been officially named COVID-19). As I was lathering up, I remembered that the Center for Disease Control and Prevention (CDC) advised people to scrub for at least 20 seconds, which is about the time it takes to sing Happy Birthday twice. I decided to try the musical self-timing method and began singing Happy Birthday to You in my head while washing my hands. When it came time to insert the name of the person celebrating a birthday, however, I froze. Who was I supposed to be singing to? \
After a few seconds of blankly staring at myself in the mirror wondering why the CDC failed to tell people who to sing Happy Birthday to, I decided I had to pick a name. Any name. I naturally chose myself and started singing the song all over again. But upon hearing myself think words, Happy birthday dear Nicole, while standing alone in a bathroom two months before my actual birthday, I cringed. My next thought was that I should dedicate my hand washing song to someone else. Do I sing to like, John Krasinski? I wondered. But before I could restart the song a third time I realized that all of these setbacks had likely brought my hand washing time to more than 20 seconds, so I simply stopped washing and turned off the water. \
Ultimately, I wouldn't say my first run at singing while scrubbing my hands went well. I was left feeling confused and annoyed, and decided to ask the internet who they sang to during their own hand washing parties. See Kally Lavoie's other Tweets \
It's clear that some people feel comfortable singing to themselves or simply humming the tune without thinking of any lyrics. But for anyone like myself unable to comfortably complete either of those tasks, here's what I suggest: If you don't personally know someone celebrating a birthday while you're washing your hands, sing to a celebrity.\
There are a bunch of online resources for learning celebrity birthdays, and though these people will never know you're celebrating their day in a restroom while washing your hands, at least you'll be singing with purpose. When I wash my hands before lunch today, I'll be singing Happy Birthday to actress and activist Connie Britton, who turns 53 today. In addition to the Friday Night Lights star, Shaquille O'Neal was born on March 6, so I may dedicate my pre-dinner hand wash to him. \
If you can't find a celebrity you feel like celebrating, you can always sing to Creed Bratton, like Michael Scott did during that one episode of The Office. And if you want to be extra cautious, you can tack on a few extra seconds to your wash by adding cha-cha-chas. \
Now that I have some clearer hand washing direction, I feel fully equipped to properly kill germs. My only remaining fear is that the song Happy Birthday can get pretty annoying after a while. So for those who grow tired of singing it, or simply refuse to ever sing it in the first place, here are some alternative 20-second tunes you can wash to instead. \
Helpful Twitter threads, like this one from @JenMonnier, list several songs with catchy 20-second choruses â€” from BeyoncÃ©'s Love On Top and Toto's Africa to Lizzo's Truth Hurts. People are sharing a slew of other ways to pass the 20 seconds it takes to submerge your hands in soap and water, too. And if all else fails, you can always sing the pizza bagel jingle. Or, you know, just count to 20. Hopefully these guidelines will help make your excessive hand washing more fun. Now if only we could master the art of not touching our faces."

category = 'lifestyle'
num_hrefs = 13
num_self_hrefs = 5
num_imgs = 5
num_videos = 2

Function taking input from website and generating "good" or "bad" rating

In [251]:
# Title input:
def title_count(title):
    count = 0
    nlp = English()
    doc = nlp(title)
    for i in doc:
        count += 1
    return count

In [252]:
# Body input:
def body_counts(body):
    count = 0
    nunique = 0
    n_non_sw = 0
    n_non_sw_unique = 0
    unique = []
    non_sw = []
    non_sw_unique = []
    nlp = English()
    doc = nlp(body)
    for i in doc:
        count += 1
        if str(i) not in unique:
            unique.append(str(i))
        if i.is_stop == False:
            non_sw.append(i)
        if (i.is_stop == False) & (str(i) not in non_sw_unique):
            non_sw_unique.append(str(i))
    nunique = len(unique)
    n_non_sw = len(non_sw)
    n_non_sw_unique = len(non_sw_unique)
    return count, nunique, n_non_sw, n_non_sw_unique

In [253]:
def prediction_info(title,
                    body,
                    num_hrefs,
                    num_self_hrefs,
                    num_imgs,
                    num_videos):
    n_tokens_title = title_count(title)
    n_tokens_content, n_unique_tokens, n_non_stop_words, n_non_stop_unique_tokens = body_counts(body)
    df_predict = pd.DataFrame({' n_tokens_title':n_tokens_title,
                               ' n_tokens_content':n_tokens_content, 
                               ' n_unique_tokens':n_unique_tokens, 
                               ' n_non_stop_words':n_non_stop_words, 
                               ' n_non_stop_unique_tokens':n_non_stop_unique_tokens,
                               ' num_hrefs':num_hrefs, 
                               ' num_self_hrefs':num_self_hrefs,
                               ' num_imgs':num_imgs, 
                               ' num_videos':num_videos}, index=[0])
    return df_predict

In [261]:
def userinput(user_input, category):
    if category == 'lifestyle':
        output = pd.concat([user_input, dfmean_lifestyle], axis=1)
    elif category == 'entertainment':
        output = pd.concat([user_input, dfmean_entertainment], axis=1)
    elif category == 'business':
        output = pd.concat([user_input, dfmean_business], axis=1)
    elif category == 'socmed':
        output = pd.concat([user_input, dfmean_socmed], axis=1)
    elif category == 'tech':
        output = pd.concat([user_input, dfmean_tech],axis=1)
    elif category == 'world':
        output = pd.concat([user_input, dfmean_world], axis=1)
    return output

In [274]:
#generating rating of 'good' or 'bad'


def detrating(category, user_df):
    if category == 'lifestyle':
        rating = LogReg_lifestyle.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')
    elif category == 'entertainment':
        rating = LogReg_entertainment.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')
    elif category == 'business':
        rating = LogReg_business.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')
    elif category == 'socmed':
        rating = LogReg_socmed.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')
    elif category == 'tech':
        rating = LogReg_tech.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')
    elif category == 'world':
        rating = LogReg_world.predict(user_df)
        if rating == 0:
            print('bad')
        else:
            print('good')

In [276]:
user_input = prediction_info(title,
                             body,
                             num_hrefs,
                             num_self_hrefs,
                             num_imgs,
                             num_videos)
user_df = userinput(user_input, category)
detrating(category, user_df)

bad